name: anfm_minimal
channels:
  - conda-forge
  - nvidia
  - pytorch
dependencies:
  - python=3.10.14
  - pytorch-cuda=12.1
  - pytorch==2.3.0
  - graph-tool
  - numpy==1.26.4=py310hb13e2d6_0
  - rdkit=2022.09.5
  - pip:
    - einops==0.8.0
    - fcd==1.2.2
    - h5py==3.11.0
    - hydra-core==1.3.2
    - joblib==1.4.2
    - lightning==2.3.0
    - loguru==0.7.2
    - pyemd==1.0.0
    - pygsp==0.5.1
    - pytorch-lightning==2.5.0.post0
    - rdkit==2024.9.4
    - scikit-learn==1.5.0
    - torch-geometric==2.5.3
    - tqdm==4.67.1
    - wandb==0.17.0